version: '3'
services:

  #Python Service
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: elastic_django_app_python
    ports:
      - "8080:8080"
    volumes:
      - ./:/elastic_django
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - ES_HOST=es7
      - ES_PORT=9200
    depends_on:
      - es7
    networks:
      - elastic

  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elastic_django_es7
    environment:
      - discovery.type=single-node
    volumes:
      - data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

volumes:
  data1:
    driver: local

networks:
  elastic:
    driver: bridge